version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
